
public class ExceptionDemo5 {

	public static void main(String[] args) {
		//this is called normal termination of the program
		int a = 10;
		int b = 5;
		int c = a+b;
		
		System.out.println("The sum of two number is : "+c);

	}

}
